"""Evidence-first presentation builders for the GroupSync web UI.

The LLM is allowed to decide *when* to call ``plan_group_sync`` or
``plan_individual_trip``.  This module turns the resulting, real Tutu payloads
into UI cards deterministically.  It therefore never needs to trust prose
generated by the model when it labels a fact as confirmed, risky, or unknown.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
import json
from typing import Any

from .geo import meeting_points_compatible, resolve_place
from .safety import RecommendationPolicy, SafetyVerdict
from .solver import GroupTripContract, checkout_ref_for_variant, inspect_offer_risks, parse_datetime


JSON = dict[str, Any]

_REJECTION_LABELS = {
    "different_hub_airport_or_station": "приезд не в ту точку встречи",
    "outside_meeting_window": "не попали в окно ожидания",
    "no_feeder_within_exact_hub_window": "нет подходящего подъезда к общему рейсу",
    "common_service_signature_mismatch": "общий рейс не совпал",
    "common_leg_not_exact_hub_to_destination": "нет прямого общего плеча от встречи до финиша",
    "strict_baggage_not_confirmed": "багаж не подтверждён",
    "missing_segments": "мало данных по сегментам",
    "hub_unknown": "точка встречи не подтверждена",
    "meeting_window_unknown": "время стыковки не подтверждено",
    "wrong_origin": "старт не из нужного города",
    "origin_unknown": "точка старта не подтверждена",
    "combination_cap_reached": "слишком много комбинаций",
}


def _as_mapping(value: Any) -> JSON:
    return dict(value) if isinstance(value, Mapping) else {}


def _as_list(value: Any) -> list[Any]:
    return list(value) if isinstance(value, Sequence) and not isinstance(value, (str, bytes)) else []


def _display_state(status: Any) -> str:
    return "confirmed" if str(status) == "pass" else ("risk" if str(status) == "risk" else "unknown")


def _safety_display_state(verdict: SafetyVerdict, *, risks_status: Any) -> str:
    if verdict.status == "recommended":
        return _display_state(risks_status)
    if verdict.status == "needs_verification":
        return "unknown"
    return "risk"


def _format_money(amount: Any, currency: Any) -> str:
    if isinstance(amount, (int, float)) and not isinstance(amount, bool):
        text = f"{amount:,.0f}".replace(",", " ")
        return f"{text} {currency or '₽'}"
    return "нужно уточнить"


def _format_minutes(value: Any) -> str:
    try:
        minutes = int(value)
    except (TypeError, ValueError):
        return "нужно уточнить"
    hours, remainder = divmod(max(0, minutes), 60)
    if hours:
        return f"{hours} ч {remainder:02d} мин"
    return f"{remainder} мин"


def _segment_route(segment: Mapping[str, Any]) -> str:
    origin = segment.get("origin_code") or "?"
    destination = segment.get("destination_code") or "?"
    number = segment.get("service_number")
    return f"{origin} → {destination}" + (f" · {number}" if number else "")


def _clock(value: Any) -> str:
    parsed = parse_datetime(value)
    if parsed is not None:
        return parsed.strftime("%H:%M")
    text = str(value or "").strip()
    if not text or text == "?":
        return "?"
    for separator in ("T", " "):
        if separator in text:
            tail = text.split(separator, 1)[1]
            if len(tail) >= 5 and tail[2] == ":":
                return tail[:5]
    if len(text) >= 5 and text[2] == ":":
        return text[:5]
    return text


def _stop_text(mapped: Mapping[str, Any], *keys: str) -> str:
    for key in keys:
        value = mapped.get(key)
        if isinstance(value, Mapping):
            nested = value.get("name") or value.get("title") or value.get("label")
            text = str(nested or "").strip()
        else:
            text = str(value or "").strip()
        if text and not text.isdigit():
            return text
    return ""


def _compose_leg_label(*, place: Any, stop: str, code: str, used_fallback: bool) -> str:
    if place is None:
        return stop or code
    city = str(place.label or "").split("·")[0].strip()
    if used_fallback and stop and city.lower() not in stop.lower():
        return f"{city}, {stop}"
    if used_fallback and city:
        return city
    return str(place.label or city or stop or code)


def _timeline_leg(
    segment: Any,
    *,
    mode: str,
    extra_route_suffix: str = "",
    fallback_origin: str | None = None,
    fallback_destination: str | None = None,
) -> JSON:
    mapped = _as_mapping(segment)
    origin = (
        resolve_place(mapped.get("origin_code"), mode=mode)
        or resolve_place(mapped.get("origin_name"), mode=mode)
        or resolve_place(mapped.get("from"), mode=mode)
    )
    destination = (
        resolve_place(mapped.get("destination_code"), mode=mode)
        or resolve_place(mapped.get("destination_name"), mode=mode)
        or resolve_place(mapped.get("to"), mode=mode)
    )
    used_fallback_origin = False
    used_fallback_destination = False
    if origin is None and fallback_origin:
        origin = resolve_place(fallback_origin, mode=mode)
        used_fallback_origin = origin is not None
    if destination is None and fallback_destination:
        destination = resolve_place(fallback_destination, mode=mode)
        used_fallback_destination = destination is not None
    origin_code = str(mapped.get("origin_code") or (origin.code if origin is not None else "") or "?")
    destination_code = str(
        mapped.get("destination_code") or (destination.code if destination is not None else "") or "?"
    )
    origin_stop = _stop_text(mapped, "origin_name", "from", "departure_station")
    destination_stop = _stop_text(mapped, "destination_name", "to", "arrival_station")
    origin_label = _compose_leg_label(
        place=origin, stop=origin_stop, code=origin_code, used_fallback=used_fallback_origin
    )
    destination_label = _compose_leg_label(
        place=destination, stop=destination_stop, code=destination_code, used_fallback=used_fallback_destination
    )
    departure = _clock(mapped.get("departure_at"))
    arrival = _clock(mapped.get("arrival_at"))
    number = mapped.get("service_number")
    line = f"{origin_label} {departure} → {destination_label} {arrival}"
    if number:
        line += f", {number}"
    line += extra_route_suffix
    leg: JSON = {
        "time": f"{departure}–{arrival}",
        "route": f"{origin_label} → {destination_label}" + (f" · {number}" if number else "") + extra_route_suffix,
        "line": line,
        "mode": str(mode or "транспорт"),
    }
    if origin is not None:
        leg["origin"] = origin.to_dict()
    if destination is not None:
        leg["destination"] = destination.to_dict()
    return leg


def _tariff_public_shape(variant: Mapping[str, Any], index: int, *, fallback: str) -> JSON:
    conditions = _as_mapping(variant.get("conditions"))
    baggage = conditions.get("baggage") or variant.get("baggage")
    details: list[str] = []
    if baggage is not None:
        details.append(f"багаж: {baggage}")
    for key, label in (("refundable", "возврат"), ("changeable", "обмен")):
        value = conditions.get(key, variant.get(key))
        if value is not None:
            details.append(f"{label}: {'да' if value is True else 'нет' if value is False else value}")
    if not details:
        details.append("условия уточняются в текущем ответе Туту")

    variant_id = str(
        variant.get("variant_id")
        or variant.get("id")
        or variant.get("offer_hash")
        or variant.get("service_class")
        or f"{fallback}-{index}"
    )
    price = _as_mapping(variant.get("price"))
    return {
        "variant_id": variant_id,
        # Compact aviation responses put the human-friendly family into
        # ``conditions.fare_family`` (for example, Light/Flex), while
        # ``service_class`` is often only ECONOMIC.  Prefer the former, but
        # keep the generic fallback for other transport modes.
        "name": str(
            variant.get("name")
            or variant.get("fare_name")
            or conditions.get("fare_family")
            or variant.get("service_class")
            or "Тариф Туту"
        ),
        "price": _format_money(price.get("amount"), price.get("currency")) if price else "цена в составе оффера",
        "details": details,
        "state": "unknown" if not conditions else "confirmed",
    }


def _expected_passenger_counts(value: Mapping[str, Any] | None) -> JSON:
    """Normalise only counts which the planning contract actually specified."""

    result: JSON = {}
    for key in ("passengers_full", "passengers_child", "passengers_infant"):
        if not isinstance(value, Mapping) or value.get(key) is None:
            continue
        try:
            count = int(value[key])
        except (TypeError, ValueError):
            continue
        if count >= 0:
            result[key] = count
    return result


def _ref_passenger_counts(checkout_ref: Mapping[str, Any]) -> JSON:
    """Read party size from a Tutu ref using documented aliases.

    Rail/bus compact refs often omit passenger fields entirely.  Missing keys
    must not be treated as a different party size.
    """

    aliases = {
        "passengers_full": ("passengers_full", "adults", "adult_count", "passengers_adult", "passengers"),
        "passengers_child": ("passengers_child", "children", "child_count"),
        "passengers_infant": ("passengers_infant", "infants", "infant_count"),
    }
    result: JSON = {}
    for canonical, keys in aliases.items():
        for key in keys:
            if key not in checkout_ref or checkout_ref[key] is None:
                continue
            if isinstance(checkout_ref[key], (Mapping, list, tuple)):
                continue
            try:
                count = int(checkout_ref[key])
            except (TypeError, ValueError):
                continue
            if count >= 0:
                result[canonical] = count
            break
    return result


def _checkout_ref_matches_expected_passengers(
    checkout_ref: Mapping[str, Any],
    expected_passengers: Mapping[str, Any],
) -> bool:
    """Do not expose a handoff returned for a different party size.

    This is deliberately checked against the original Tutu ref in addition to
    the final server-side guard.  The presentation layer prevents a misleading
    clickable card; the guard later protects the actual MCP call.
    """

    actual = _ref_passenger_counts(checkout_ref)
    if not actual:
        return True
    for key, expected in _expected_passenger_counts(expected_passengers).items():
        if key not in actual:
            continue
        if actual[key] != expected:
            return False
    return True


def _same_checkout_ref(left: Mapping[str, Any], right: Mapping[str, Any]) -> bool:
    """Compare opaque JSON refs structurally without normalising their data."""

    try:
        return json.dumps(left, ensure_ascii=False, sort_keys=True, separators=(",", ":")) == json.dumps(
            right,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    except (TypeError, ValueError):
        return False


def _component_from_raw_offer(
    raw_offer: Mapping[str, Any],
    *,
    component_ref: str,
    title: str,
    scope: str,
    expected_passengers: Mapping[str, Any] | None = None,
    selected_checkout_ref: Mapping[str, Any] | None = None,
) -> tuple[JSON | None, JSON | None]:
    """Return browser-safe unit + private checkout component.

    A tariff becomes selectable only if Tutu returned an exact checkout ref,
    including the documented aviation case where its variant ``offer_hash``
    and ``service_class`` refine the parent ref.  We never create a URL or
    guess opaque data from passenger counts.
    """

    variants = _as_list(raw_offer.get("variants"))
    private_variants: list[JSON] = []
    public_tariffs: list[JSON] = []
    expected = _expected_passenger_counts(expected_passengers)
    passenger_count_mismatch = False

    for index, candidate in enumerate(variants, 1):
        variant = _as_mapping(candidate)
        ref = checkout_ref_for_variant(raw_offer, variant)
        if ref is None:
            # It may be visible, but the MCP did not provide an exact handoff
            # representation for it.
            continue
        # A scenario is priced and risk-checked for a concrete combination of
        # fares.  Never re-open its parent offer as an arbitrary mix-and-match
        # tariff menu: that could expose, for example, a no-baggage fare after
        # the solver selected the baggage-included one.
        if selected_checkout_ref is not None and not _same_checkout_ref(ref, selected_checkout_ref):
            continue
        if not _checkout_ref_matches_expected_passengers(ref, expected):
            if _ref_passenger_counts(ref):
                passenger_count_mismatch = True
            continue
        public = _tariff_public_shape(variant, index, fallback=component_ref)
        snapshot = dict(raw_offer)
        snapshot["selected_variant"] = dict(variant)
        snapshot["checkout_ref"] = dict(ref)
        private_variants.append(
            {
                **public,
                "checkout_ref": dict(ref),
                "offer": snapshot,
            }
        )
        public_tariffs.append(public)

    # Some MCP offers provide only a single exact ref.  It is safe to expose
    # it as one returned tariff, but it is not safe to invent refs for the
    # other visible variants.
    top_ref = raw_offer.get("checkout_ref")
    transport = str(raw_offer.get("transport") or raw_offer.get("mode") or "").lower()
    avia_offer = any(token in transport for token in ("avia", "air", "flight", "самол"))
    # A top-level ref alongside aviation fare families is commonly a generic
    # search handle, not the exact fare the person selected.  Rail/bus compact
    # replies often attach dummy variants without their own refs; reuse the
    # offer-level handle in that case.
    if (
        isinstance(top_ref, Mapping)
        and (not variants or not avia_offer)
        and not private_variants
        and (selected_checkout_ref is None or _same_checkout_ref(top_ref, selected_checkout_ref))
    ):
        if _checkout_ref_matches_expected_passengers(top_ref, expected):
            base = variants[0] if variants and isinstance(variants[0], Mapping) else {}
            public = _tariff_public_shape(_as_mapping(base), 1, fallback=f"{component_ref}-returned")
            public["variant_id"] = f"{component_ref}-returned"
            public["name"] = f"{public['name']} · вариант, возвращённый Туту"
            private_variants.append(
                {
                    **public,
                    "checkout_ref": dict(top_ref),
                    "offer": dict(raw_offer),
                }
            )
            public_tariffs.append(public)
        elif _ref_passenger_counts(top_ref):
            passenger_count_mismatch = True

    if not private_variants:
        note = "Туту не вернул точный checkout-ref для этого варианта: выберите его на стороне Туту после проверки."
        if passenger_count_mismatch and expected:
            note = (
                "Туту вернул тариф для другого числа пассажиров; ссылку не показываем, "
                "чтобы не оформить поездку на неверный состав группы."
            )
        return (
            {
                "component_ref": component_ref,
                "title": title,
                "scope": scope,
                "handoff_note": note,
                "tariffs": [],
            },
            None,
        )

    return (
        {
            "component_ref": component_ref,
            "title": title,
            "scope": scope,
            "handoff_note": "После выбора будет создана ссылка на Туту; это не бронирование.",
            "tariffs": public_tariffs,
        },
        {
            "component_ref": component_ref,
            # Keep this at the component level.  GroupSyncService forwards it
            # to checkout_handoff_guard, so it is compared with the Tutu ref
            # rather than copied from the same ref into the expectation.
            "expected_passengers": expected,
            "variants": private_variants,
        },
    )


def _evidence_from_risks(risks: Mapping[str, Any]) -> list[JSON]:
    evidence: list[JSON] = []
    for item in _as_list(risks.get("findings"))[:6]:
        finding = _as_mapping(item)
        evidence.append(
            {
                "state": _display_state(finding.get("status")),
                "title": str(finding.get("code") or "Проверка маршрута").replace("_", " "),
                "body": str(finding.get("message") or "Нет подробностей в текущем ответе."),
                "source": "Tutu MCP + детерминированная проверка GroupSync",
            }
        )
    return evidence


def _empty_search_reason(summary: Mapping[str, Any], *, hub: str = "", destination: str = "") -> str:
    if not summary:
        return "Туту не вернул подходящие варианты по этому маршруту."
    if summary.get("common_leg_not_exact_hub_to_destination"):
        place = f"из «{hub}» в «{destination}»" if hub and destination else "от точки встречи до финиша"
        return (
            f"Нет одного общего билета {place}. "
            "Группа едет так: каждый доезжает до встречи своими билетами, дальше все одним рейсом, поездом или автобусом. "
            "Если нужен маршрут с пересадкой на общем плече — укажите другую станцию встречи, другую дату "
            "или поищите каждого по отдельности."
        )
    if summary.get("no_feeder_within_exact_hub_window") or summary.get("outside_meeting_window"):
        return (
            "До встречи билеты нашлись, но к общему отправлению никто не успевает в вашем окне ожидания. "
            "Увеличьте окно, сдвиньте дату или точку встречи."
        )
    if summary.get("hub_unknown"):
        return (
            f"Билеты до точки встречи нашлись, но Туту не назвал вокзал прибытия ({hub or 'хаб'}). "
            "Укажите конкретный вокзал встречи."
        )
    if summary.get("different_hub_airport_or_station"):
        return (
            f"Поезда или автобусы нашлись, но они приезжают не в ту точку встречи ({hub or 'хаб'}). "
            "Для группы встреча должна быть в одном городе и на одном вокзале или автовокзале."
        )
    if summary.get("wrong_origin"):
        return "Туту вернул варианты не из тех городов, откуда едут участники."
    return "Подходящей стыковки на эти дату и условия не нашлось. Попробуйте другую дату или искать по одному."


def _meeting_window_detail(excluded: Sequence[Any], *, hub: str, max_wait_minutes: int) -> str:
    """Explain the concrete timing clash behind an empty group search."""

    waits: dict[str, list[int]] = {}
    blockers: list[str] = []
    for item in excluded:
        mapping = _as_mapping(item)
        reason = mapping.get("reason")
        person = str(mapping.get("participant_id") or "").strip()
        if reason == "no_feeder_within_exact_hub_window" and person and person not in blockers:
            blockers.append(person)
            continue
        if reason != "outside_meeting_window":
            continue
        value = mapping.get("wait_minutes")
        if not isinstance(value, int) or isinstance(value, bool):
            continue
        waits.setdefault(person or "участник", []).append(value)
    if not blockers:
        return ""

    # Only the participants who left no usable feeder explain the empty result.
    too_late = [person for person in blockers if waits.get(person) and max(waits[person]) < 0]
    if too_late:
        names = ", ".join(too_late)
        verb = "приезжает" if len(too_late) == 1 else "приезжают"
        place = hub or "точку встречи"
        return (
            f"{names} {verb} в {place} уже после того, как уходит последний общий рейс в этот день. "
            "Возьмите общий рейс на следующий день или выезжайте накануне."
        )
    positive = [value for person in blockers for value in waits.get(person, []) if value >= 0]
    if positive:
        names = ", ".join(blockers)
        return (
            f"У участника {names} ближайшая стыковка даёт ожидание {_format_minutes(min(positive))}, "
            f"а в договоре максимум {_format_minutes(max_wait_minutes)}. Увеличьте окно ожидания или сдвиньте дату."
        )
    return ""


def _rejection_summary(summary: Mapping[str, Any], *, hub: str = "", destination: str = "") -> str:
    if not summary:
        return ""
    return _empty_search_reason(summary, hub=hub, destination=destination)


def _contract_card(contract: GroupTripContract) -> JSON:
    participants = [
        {"name": participant.id, "origin": participant.origin_code or "нужно уточнить"}
        for participant in contract.participants
    ]
    route = " · ".join(item["origin"] for item in participants) + f" → {contract.hub_code} → {contract.destination_code}"
    return {
        "title": "Договор группы",
        "route": route,
        "participants": participants,
        "hard_constraints": [
            {"label": f"Точка встречи: именно {contract.hub_code}", "state": "confirmed"},
            {
                "label": f"Окно ожидания: {_format_minutes(contract.min_wait_minutes)} – {_format_minutes(contract.max_wait_minutes)}",
                "state": "confirmed",
            },
            {"label": f"Общее последнее плечо до {contract.destination_code}", "state": "confirmed"},
        ],
        "soft_preferences": [
            "Отдельные фидеры не считаются защищённой пересадкой.",
            (
                f"Нужен подтверждённый багаж: {contract.required_checked_baggage_pieces} мест(а)."
                if contract.required_checked_baggage_pieces
                else "Зарегистрированный багаж не задан как обязательный."
            ),
        ],
    }


def build_group_presentation(
    *,
    contract: Mapping[str, Any],
    solver_result: Mapping[str, Any],
    raw_common_by_id: Mapping[str, Mapping[str, Any]],
    raw_feeder_by_id: Mapping[str, Mapping[str, Any]],
    common_expected_passengers: Mapping[str, Any] | None = None,
    feeder_expected_passengers: Mapping[str, Mapping[str, Any]] | None = None,
    query: str,
) -> tuple[JSON, list[JSON]]:
    """Build safe UI data and separate private checkout components.

    The returned ``presentation`` never contains `checkout_ref`.  Its sibling
    `checkout_components` is consumed only by :class:`RunStore` on the server.
    """

    typed_contract = GroupTripContract.from_mapping(contract)
    scenarios_out: list[JSON] = []
    private_components: list[JSON] = []
    timeline: list[JSON] = []
    raw_scenarios = _as_list(solver_result.get("scenarios"))
    feeder_counts = feeder_expected_passengers or {}
    policy = RecommendationPolicy()

    for index, item in enumerate(raw_scenarios[:1], 1):
        scenario = _as_mapping(item)
        scenario_id = f"scenario-{index}"
        tone, title = "price", "Вариант"
        common = _as_mapping(scenario.get("common_offer"))
        common_id = str(common.get("id") or "")
        raw_common = raw_common_by_id.get(common_id, common)
        metrics = _as_mapping(scenario.get("metrics"))
        risks = _as_mapping(scenario.get("risks"))
        signature = _as_mapping(scenario.get("common_service_signature"))
        verdict = policy.evaluate(typed_contract, scenario)
        status = _safety_display_state(verdict, risks_status=risks.get("overall_status"))
        allow_cta = verdict.allows_checkout

        booking_units: list[JSON] = []
        if allow_cta:
            unit, private = _component_from_raw_offer(
                raw_common,
                component_ref=f"{scenario_id}:common",
                title=f"Общее плечо · {_segment_route(signature)}",
                scope=f"Один общий {signature.get('mode') or 'сегмент'} для {len(typed_contract.participants)} участников",
                expected_passengers=common_expected_passengers,
                selected_checkout_ref=common.get("checkout_ref") if isinstance(common.get("checkout_ref"), Mapping) else None,
            )
            if unit:
                booking_units.append(unit)
            if private:
                private_components.append(private)

        scenario_timeline: list[JSON] = []
        for feeder_index, feeder_value in enumerate(_as_list(scenario.get("feeders")), 1):
            feeder = _as_mapping(feeder_value)
            participant_id = str(feeder.get("participant_id") or f"Участник {feeder_index}")
            normalized = _as_mapping(feeder.get("offer"))
            offer_id = str(normalized.get("id") or "")
            raw_feeder = raw_feeder_by_id.get(offer_id, normalized)
            if allow_cta:
                unit, private = _component_from_raw_offer(
                    raw_feeder,
                    component_ref=f"{scenario_id}:feeder:{participant_id}",
                    title=f"Фидер {participant_id} · до {typed_contract.hub_code}",
                    scope="Отдельное оформление до точки встречи; это не единая бронь с общим плечом.",
                    expected_passengers=feeder_counts.get(participant_id),
                    selected_checkout_ref=(
                        normalized.get("checkout_ref") if isinstance(normalized.get("checkout_ref"), Mapping) else None
                    ),
                )
                if unit:
                    booking_units.append(unit)
                if private:
                    private_components.append(private)

            segments = _as_list(normalized.get("segments"))
            last = _as_mapping(segments[-1]) if segments else {}
            feeder_mode = str(normalized.get("mode") or "транспорт")
            legs = [_timeline_leg(segment, mode=feeder_mode) for segment in segments]
            if signature:
                legs.append(
                    _timeline_leg(
                        signature,
                        mode=str(signature.get("mode") or "транспорт"),
                        extra_route_suffix=" · общий сегмент",
                        # The signature carries codes only, so an unmapped
                        # station id still gets its city from the contract.
                        fallback_origin=typed_contract.hub_code,
                        fallback_destination=typed_contract.destination_code,
                    )
                )
            scenario_timeline.append(
                {
                    "person": participant_id,
                    "arrival": f"{last.get('arrival_at') or '?'} · {typed_contract.hub_code}",
                    "wait": f"{_format_minutes(feeder.get('wait_minutes'))} до общей услуги",
                    "legs": legs,
                }
            )

        if not timeline:
            timeline = scenario_timeline

        has_tariff = any(unit.get("tariffs") for unit in booking_units)
        if allow_cta and has_tariff:
            subtitle = "Перед оплатой проверьте рейс, цену и пассажиров на Туту."
        elif allow_cta:
            notes = [str(unit.get("handoff_note") or "") for unit in booking_units]
            subtitle = next((note for note in notes if note), "Туту нашёл вариант, но не дал точную ссылку на оформление.")
        else:
            subtitle = verdict.reason or "Этот вариант нельзя рекомендовать к оформлению."
        scenarios_out.append(
            {
                "id": scenario_id,
                "tone": tone,
                "title": title,
                "subtitle": subtitle,
                "state": status,
                "safety_verdict": verdict.status,
                "safety_reason": verdict.reason,
                "metrics": [
                    {"label": "Итого", "value": _format_money(metrics.get("total_price"), metrics.get("currency"))},
                    {"label": "Макс. ожидание", "value": _format_minutes(metrics.get("max_wait_minutes"))},
                    {"label": "Общее плечо", "value": _segment_route(signature)},
                ],
                "evidence": [],
                "booking_units": booking_units,
            }
        )

    recommended_count = sum(1 for item in scenarios_out if item.get("safety_verdict") == "recommended")
    excluded = _as_mapping(solver_result.get("excluded_summary"))
    if recommended_count:
        summary = f"Нашёл вариант встречи в {typed_contract.hub_code}."
        rejection_summary = ""
    elif scenarios_out:
        summary = f"Стыковка в {typed_contract.hub_code} нашлась, но оформить её пока нельзя."
        rejection_summary = scenarios_out[0].get("subtitle") or ""
    else:
        summary = _empty_search_reason(
            excluded, hub=typed_contract.hub_code, destination=typed_contract.destination_code
        )
        detail = _meeting_window_detail(
            _as_list(solver_result.get("excluded")),
            hub=typed_contract.hub_code,
            max_wait_minutes=typed_contract.max_wait_minutes,
        )
        if detail:
            summary = detail
        rejection_summary = ""

    presentation: JSON = {
        "query": query,
        "summary": summary,
        "contract": _contract_card(typed_contract),
        "timeline": timeline,
        "scenarios": scenarios_out,
        "rejection_summary": rejection_summary,
    }
    return presentation, private_components


_MODE_LABELS = {"avia": "самолёт", "rail": "поезд", "bus": "автобус"}


def _individual_contract_card(
    *,
    origin: str,
    destination: str,
    mode: str,
    departure_date: str,
    adults: int,
    min_wait_minutes: int,
    max_wait_minutes: int,
) -> JSON:
    mode_label = _MODE_LABELS.get(mode, mode)
    return {
        "title": "Поездка одного человека",
        "route": f"{origin} → {destination}",
        "participants": [{"name": "Путешественник", "origin": origin}],
        "hard_constraints": [
            {"label": f"Маршрут: {origin} → {destination}", "state": "confirmed"},
            {"label": f"Дата: {departure_date}", "state": "confirmed"},
            {"label": f"Транспорт: {mode_label}", "state": "confirmed"},
            {"label": f"Пассажиры: {adults}", "state": "confirmed"},
            {
                "label": f"Окно стыковки: {_format_minutes(min_wait_minutes)} – {_format_minutes(max_wait_minutes)}",
                "state": "confirmed",
            },
        ],
        "soft_preferences": [
            "Оформление доступно только после выбора точного тарифа в интерфейсе.",
            "Самостоятельная пересадка внутри билета проверяется по запасу времени.",
        ],
    }


def _individual_connection_minutes(offer: Mapping[str, Any]) -> list[int]:
    segments = _as_list(offer.get("segments"))
    waits: list[int] = []
    for previous, following in zip(segments, segments[1:]):
        left = _as_mapping(previous)
        right = _as_mapping(following)
        first = parse_datetime(left.get("arrival_at"))
        second = parse_datetime(right.get("departure_at"))
        if first is None or second is None:
            continue
        if (first.tzinfo is None) != (second.tzinfo is None):
            continue
        waits.append(int((second - first).total_seconds() // 60))
    return waits


def build_individual_presentation(
    *,
    origin: str,
    destination: str,
    mode: str,
    departure_date: str,
    adults: int,
    min_wait_minutes: int,
    max_wait_minutes: int,
    items: Sequence[Mapping[str, Any]],
    query: str,
    excluded_summary: Mapping[str, Any] | None = None,
) -> tuple[JSON, list[JSON]]:
    """Build A→B cards and private checkout components for one traveller.

    ``items`` are already SafetyGate-classified.  Public JSON never contains
    ``checkout_ref``; CTA exists only for ``recommended`` fares.
    """

    scenarios_out: list[JSON] = []
    private_components: list[JSON] = []
    timeline: list[JSON] = []
    expected_passengers = {"passengers_full": adults}

    for index, item in enumerate(list(items)[:1], 1):
        payload = _as_mapping(item)
        scenario_id = f"scenario-{index}"
        tone, title = "price", "Вариант"
        raw_offer = _as_mapping(payload.get("raw_offer"))
        offer = _as_mapping(payload.get("offer"))
        verdict = payload.get("verdict")
        if not isinstance(verdict, SafetyVerdict):
            verdict = RecommendationPolicy().evaluate_offer(
                offer or raw_offer,
                max_wait_minutes=max_wait_minutes,
                min_wait_minutes=min_wait_minutes,
            )
        selected_ref = payload.get("selected_checkout_ref")
        selected_checkout_ref = selected_ref if isinstance(selected_ref, Mapping) else None
        risks = inspect_offer_risks(raw_offer or offer)
        status = _safety_display_state(verdict, risks_status=risks.get("overall_status"))
        allow_cta = verdict.allows_checkout
        segments = _as_list(offer.get("segments")) or _as_list(raw_offer.get("segments"))
        last = _as_mapping(segments[-1]) if segments else {}
        first = _as_mapping(segments[0]) if segments else {}
        checkout = raw_offer.get("checkout_ref") if isinstance(raw_offer.get("checkout_ref"), Mapping) else {}
        meta = raw_offer.get("meta") if isinstance(raw_offer.get("meta"), Mapping) else {}
        city_from = str(checkout.get("city_from") or meta.get("from") or origin)
        city_to = str(checkout.get("city_to") or meta.get("to") or destination)
        route_origin = str(city_from or first.get("origin_code") or origin)
        route_destination = str(city_to or last.get("destination_code") or destination)
        connections = _individual_connection_minutes(offer if offer.get("segments") else {"segments": segments})
        booking_units: list[JSON] = []
        if allow_cta:
            unit, private = _component_from_raw_offer(
                raw_offer or offer,
                component_ref=f"{scenario_id}:ticket",
                title=f"{route_origin} → {route_destination}",
                scope=f"Один билет для {adults} пасс. · {_MODE_LABELS.get(mode, mode)}",
                expected_passengers=expected_passengers,
                selected_checkout_ref=selected_checkout_ref,
            )
            if unit:
                booking_units.append(unit)
            if private:
                private_components.append(private)

        legs = [
            _timeline_leg(
                segment,
                mode=str(offer.get("mode") or mode),
                fallback_origin=city_from,
                fallback_destination=city_to,
            )
            for segment in segments
        ]
        person_timeline = {
            "person": "Путешественник",
            "arrival": f"{last.get('arrival_at') or '?'} · {route_destination}",
            "wait": (
                f"{_format_minutes(min(connections))} до следующего сегмента"
                if connections
                else "без пересадки"
            ),
            "legs": legs,
        }
        if not timeline:
            timeline = [person_timeline]

        price = _as_mapping(offer.get("price"))
        has_tariff = any(unit.get("tariffs") for unit in booking_units)
        if allow_cta and has_tariff:
            subtitle = "Перед оплатой проверьте рейс, цену и пассажиров на Туту."
        elif allow_cta:
            notes = [str(unit.get("handoff_note") or "") for unit in booking_units]
            subtitle = next((note for note in notes if note), "Туту нашёл вариант, но не дал точную ссылку на оформление.")
        else:
            subtitle = verdict.reason or "Этот вариант нельзя рекомендовать к оформлению."
        scenarios_out.append(
            {
                "id": scenario_id,
                "tone": tone,
                "title": title,
                "subtitle": subtitle,
                "state": status,
                "safety_verdict": verdict.status,
                "safety_reason": verdict.reason,
                "metrics": [
                    {"label": "Итого", "value": _format_money(price.get("amount"), price.get("currency"))},
                    {
                        "label": "Пересадки",
                        "value": "прямой" if len(segments) <= 1 else f"{max(0, len(segments) - 1)}",
                    },
                    {
                        "label": "Мин. стыковка",
                        "value": _format_minutes(min(connections)) if connections else "нет",
                    },
                ],
                "evidence": [],
                "booking_units": booking_units,
            }
        )

    recommended_count = sum(1 for item in scenarios_out if item.get("safety_verdict") == "recommended")
    excluded = _as_mapping(excluded_summary)
    if recommended_count:
        summary = f"Нашёл вариант {origin} → {destination}."
        rejection_summary = ""
    elif scenarios_out:
        summary = f"Вариант {origin} → {destination} нашёлся, но оформить его пока нельзя."
        rejection_summary = str(scenarios_out[0].get("subtitle") or "")
    elif excluded:
        summary = _empty_search_reason(excluded, hub=origin, destination=destination)
        rejection_summary = ""
    else:
        summary = f"По маршруту {origin} → {destination} подходящих билетов не нашлось. Попробуйте другую дату или другой вид транспорта."
        rejection_summary = ""

    presentation: JSON = {
        "query": query,
        "summary": summary,
        "contract": _individual_contract_card(
            origin=origin,
            destination=destination,
            mode=mode,
            departure_date=departure_date,
            adults=adults,
            min_wait_minutes=min_wait_minutes,
            max_wait_minutes=max_wait_minutes,
        ),
        "timeline": timeline,
        "scenarios": scenarios_out,
        "rejection_summary": rejection_summary,
    }
    return presentation, private_components
